name: PHPCS Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run PHPCS
        run: |
          export PATH="$PATH:$HOME/.composer/vendor/bin"
          phpcs --standard=WordPress /path/to/your/php/files
