name: Install WordPress Coding Standards

on:
  push:
    branches:
      - main

jobs:
  install-wordpress-coding-standards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install WordPress Coding Standards globally
        run: |
          npm install --global @wordpress/coding-standards

      - name: Verify WordPress Coding Standards installation
        run: |
          wpcs --version  # Verify installation
